# Generated by Django 4.2.2 on 2023-06-11 22:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_tours"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
