# Generated by Django 4.2.2 on 2023-06-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.CharField(blank=True, max_length=50, null=True)),
                ("price", models.CharField(blank=True, max_length=50, null=True)),
                ("image1", models.URLField(blank=True, null=True)),
                ("image2", models.URLField(blank=True, null=True)),
                ("dayDescription", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=50, null=True)),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Tours",
        ),
    ]
