# Generated by Django 4.2.2 on 2023-06-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=10, null=True)),
                ("message", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
